FROM hashicorp/terraform:0.13.5

ARG AWS_CLI_VERSION

# Install AWS CLI
RUN apk add --no-cache python3 py3-pip \
    && pip3 install --upgrade pip \
    && pip3 install awscli==${AWS_CLI_VERSION} \
    && rm -rf /var/cache/apk/*

# Default directory is /aws-accounts
WORKDIR /aws-accounts